# Generated by Django 2.1.2 on 2018-11-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181127_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_date',
        ),
    ]
