# Generated by Django 2.1.2 on 2018-11-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_number_of_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_answer',
            field=models.SmallIntegerField(default=0, max_length=5),
        ),
    ]
