# Generated by Django 2.1.2 on 2018-11-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181127_0959'),
        ('quiz', '0011_auto_20181127_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_quizzes', to='courses.Chapter'),
            preserve_default=False,
        ),
    ]
