# Generated by Django 2.1.2 on 2018-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20181128_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
