# Generated by Django 2.1.2 on 2018-11-28 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0014_auto_20181128_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(through='quiz.TakenQuiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
