# Generated by Django 2.1.2 on 2018-11-28 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quiz_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number_of_answer',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(4)]),
        ),
    ]
