# Generated by Django 2.1.2 on 2018-11-08 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=200)),
                ('topic_message', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=30)),
                ('comment_count', models.IntegerField(default=1)),
                ('stamp_created', models.DateTimeField(auto_now_add=True)),
                ('stamp_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Topic'),
        ),
    ]
