# Generated by Django 2.1.2 on 2018-11-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_topic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'get_latest_by': 'id'},
        ),
    ]
