# Generated by Django 2.1.2 on 2018-12-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
    ]
