# Generated by Django 2.1.2 on 2018-12-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_of_chapter', to='courses.Chapter'),
        ),
    ]
